### ISSUE TITLE
Connecting to Ethereum Wallet

### ISSUE THREAD

**Issue by joshterrill** [hiddentao/geth-private#2]
I installed `geth-private` and ran it on my mac. Everything appeared to be in working order, but when I ran the latest version of Ethereum Wallet, I don't believe it connected to `geth-private`. The testnet that it connected to seemed to be the regular Ethereum testnet. I am basing this off the fact that when the wallet opened, it showed TESTNET on it, and had the two testnet accounts I had on the Ethereum testnet along with the same balances that I had on the Ethereum testnet. How can I get the Ethereum Wallet to connect to the `geth-private` network that I'm running in a terminal? Or how can I tell if it's connecting to the right place?

**Comment by hiddentao** [comment]
What OS are you on?

In order for the wallet to connect to geth-private you need to run geth-private with the IPC path set to the one the wallet normally uses. OR you have to run the wallet and tell it to connect to RPC over HTTP (`--rpc http://localhost:8545`).

**Comment by joshterrill** [comment]
I'm on Mac. Okay, what is an IPC and where is its default path? And the other option is running the wallet with the `rpc` flag set to the port that `geth-private` is running?

**Comment by hiddentao** [comment]
The wallet communicates with geth via IPC (Inter-process communication). This is normally a file called `geth.ipc` and it's usually located (for Mac) in `~/Library/Ethereum/geth.ipc`. So try starting geth-private with:

`geth-private --datadir ~/Library/Ethereum`.

Then start the wallet and see if it works.

**Comment by hiddentao** [comment]
If you ever want to find out where geth stores data (and thus the IPC file) by default:

``` shell
$ geth --help | grep datadir
  --datadir "/Users/ram/Library/Ethereum"   Data directory for the databases and keystore
  --keystore                    Directory for the keystore (default = inside the datadir)
  --ipcpath "geth.ipc"  Filename for IPC socket/pipe within the datadir (explicit paths escape it)
```

**Comment by joshterrill** [comment]
Thanks for the response. So I was able to connect to it with ethereum wallet. These were the startup options I gave it...

```
geth-private --balance 100 --port 10023 --datadir ~/Library/Ethereum/
Geth is now running (pid: 35220).

Etherbase:  f3cb6350a71ecc6b7c6721540177ef4886efd2ee
Data folder:    /Users/****/Library/Ethereum/

To access:  geth attach ipc:///Users/****/Library/Ethereum//geth.ipc
```

I thought that running that would make it automine until it reached 100, but when i started ethereum wallet, it says balance was 0 and waiting for blocks. So I ran `geth attach ipc:///Users/****/Library/Ethereum//geth.ipc` in another window and typed `miner.start()`, it returned true, but still no blocks or balance. What should I do?

**Comment by hiddentao** [comment]
Try running geth-private with `-v`

You should see the mining happening. If not please report back here.

**Comment by joshterrill** [comment]
`-v` certainly seems like it starts to mine. Though it says that it's downloading DAG. I thought that if I'm running a private test-net, it would generate the first genesis block on it's own right away? Maybe I am misunderstanding what a private test-net is? Does it actually sync with the actual testnet?

**Comment by hiddentao** [comment]
It needs to generate a DAG first in order to start mining (it's for the Ethash mining algorithm). This usually only needs to happen once.

**Comment by joshterrill** [comment]
Ah okay, I was misunderstanding what the DAG was, then. Thanks!
